### ISSUE TITLE
Guest machine in poweroff state so does not boot

### ISSUE THREAD

**Issue by lluang** [charlesflynn/agiledata#10]
When I try 'vagrant up', the system downloads the precise64, but I get the following:

---

:~/Documents/learning/agiledatascience/agiledata$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Clearing any previously set forwarded ports...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

---

When I look at the virtualbox VM and try to start it, I get the following message:

---

Failed to open a session for the virtual machine precise64_1395273397325_16522.

VT-x features locked or unavailable in MSR. (VERR_VMX_MSR_LOCKED_OR_DISABLED).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: Console
Interface: IConsole {db7ab4ca-2a3f-4183-9243-c1208da92392}

---

I am using Ubuntu 13.10, Virtualbox 4.2.16, Vagrant 1.4.3.  Any ideas?

**Comment by charlesflynn** [comment]
Hey there, VT-x is Intel's hardware support for virtualization. So your hardware doesn't have it enabled, but the VM is expecting it. You can either enable VT-x in your host machine's BIOS, or disable it in the VM settings under System -> Acceleration (docs are [here](http://www.virtualbox.org/manual/ch03.html#idp54948880))
