### ISSUE TITLE
What is the host name and password?

### ISSUE THREAD

**Issue by wilsoncao** [charlesflynn/agiledata#11]
Hi,

I cannot login, and I don't know the host name and the password? What are they?

**Comment by charlesflynn** [comment]
Hey there, missed seeing this issue, sorry for the slow response. The agiledata environment is a Vagrant box, so you use the standard [vagrant ssh](http://docs.vagrantup.com/v2/cli/ssh.html) command to get in.

**Comment by 10cl** [comment]
user：vagrant
pass：vagrant
