### ISSUE TITLE
Documentation: Installing vagrant-salt requires ruby-dev

### ISSUE THREAD

**Issue by lluang** [charlesflynn/agiledata#8]
I was getting the following error when trying to install 

```
Installing the 'vagrant-salt' plugin. This can take a few minutes...
/usr/lib/ruby/1.9.1/rubygems/installer.rb:556:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:4:in `<main>'
```

I eventually figured out that what was missing was the ruby-dev package (Ubuntu), essentially, it is not enough to have Ruby on the system, but one needs the development libraries.

Suggestion fix:  Add to documentation that the development libraries for Ruby are required. (I don't know enough about Ruby to be able to be more specific than that)

**Comment by charlesflynn** [comment]
Thanks for letting me know. I've added a note about that requirement, and also changed the docs to note that Salty Vagrant is deprecated in the current version of Vagrant.
